Add bookings
NatalieFilippi/java-shareit pull request #3
Opened 2022-09-07 12:40 UTC by NatalieFilippi

2022-09-08 09:39 UTC, alexache requested changes

2022-09-08 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  /**
Комментарии можно бы убрать

2022-09-08 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoWithBookerAndItem.java
> +public class BookingDtoWithBookerAndItem {
Не до конца уверен. что нужен этот отдельный класс вместо использования BookingDto. Есть нюансы с прохождением постман тестов?

2022-09-08 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Item> items = itemStorage.findAllByOwnerOrderById(userId).stream().collect(Collectors.toList());
Мне кажется, здесь не нужно делать 2 запроса вместо одного. Вполне можно получать все вещи через репозиторий с использованием айди владельца (item.ownerId) и доп условиями, которые описаны ниже

2022-09-08 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            return itemStorage.findAllByOwnerOrderById(userId).stream().map(ItemMapper::toItemDto).map(i -> this.addBookings(userId, i)).collect(Collectors.toList());
Выглядит немного сложно. Я бы предложил попробовать немного упростить и уменьшить количество запросов. Например, запросить все подтвержденные бронирования одним отдельным запросом, и использовать результат для составления информации о следующихЁпрошлых бронированиях

2022-09-08 09:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Booking> booking = bookingRepository.findAllByBooker_IdAndEndBeforeOrderByStartDesc(userId, LocalDateTime.now());
А нельзя ли в этот запрос добавить сразу и itemId, чтобы не получать все бронирования (которые не нужны)

2022-09-08 10:39 UTC, NatalieFilippi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoWithBookerAndItem.java
> +public class BookingDtoWithBookerAndItem {
Да, есть. Во входящем Dto нам присылают айдишники пользователя и вещи, а в ответе для проверки просят сами сущности.

2022-09-08 10:52 UTC, NatalieFilippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Item> items = itemStorage.findAllByOwnerOrderById(userId).stream().collect(Collectors.toList());
Насколько я поняла из теории, то запросные методы могут работать с данными из одной таблицы. Owner в этой таблице нет, поэтому я искала его через его вещи. Но могу переписать все запросы на @Query, тогда запрос будет один

2022-09-08 12:55 UTC, NatalieFilippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Booking> booking = bookingRepository.findAllByBooker_IdAndEndBeforeOrderByStartDesc(userId, LocalDateTime.now());
точно

2022-09-08 14:15 UTC, NatalieFilippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            return itemStorage.findAllByOwnerOrderById(userId).stream().map(ItemMapper::toItemDto).map(i -> this.addBookings(userId, i)).collect(Collectors.toList());
Надо для каждой вещи собрать комментарии и инфу по бронированием. Не вижу адекватного способа, как это сделать одним запросом, может, опыта не хватает. Если выгружать таблицу по бронированием, то её надо будет парсить много-много раз, чтобы найти нужную вещь, а потом среди всех её бронирований найти следующее и текущее. Но я изменила свой код, как, мне кажется, сделала его более логичным. Вынесла метод поиска вещи в отдельный кастомный интерфейс, собрала там всю логику по комментам и броням. И теперь метод поиска всех вещей автора сводится к тому, что надо найти все вещи автора, а потом каждую дополнить инфой.

2022-09-09 19:40 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoWithBookerAndItem.java
> +public class BookingDtoWithBookerAndItem {
Да, тогда проблема скорее в названиях, Можно одно назвать BookingRequestDto, а другое BookingDto, чтобы лучше понимать, откуда разница

2022-09-09 19:42 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Item> items = itemStorage.findAllByOwnerOrderById(userId).stream().collect(Collectors.toList());
Да, я имел в виду @Query, можно переписать только один запрос, а другие оставить как есть (кроме случаев где  использование данных из нескольких таблиц может иметь смысл)

2022-09-09 19:50 UTC, alexache approved these changes

2022-09-09 19:50 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(value = "select * from bookings b join items i on b.item_id=i.id where owner_id = ?1 order by start_date desc", nativeQuery = true)
Можно бы обойтись и не-nativeQuery (а просто JPQL), выглядело бы даже попроще

2022-09-13 06:55 UTC, merged