Add item requests
NatalieFilippi/java-shareit pull request #5
Opened 2022-09-20 06:11 UTC by NatalieFilippi

2022-09-21 21:08 UTC, alexache requested changes

2022-09-21 21:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/unittests/ItemRequestTests.java
> +}
Можно бы еще добавить тест, когда не найден юзер по айди (метод validateOwner)

2022-09-21 21:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +                    ItemMapper.toItemDto(item)).collect(Collectors.toList()));
Можно писать ItemMapper::toItemDto в методе map

2022-09-21 21:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestServiceImpl.java
> +        List<ItemRequestDto> itemRequestDtos = pages.map(i -> RequestMapper.toRequestDto(i)).toList();
Здесь  тоже можно внутри метода мап написать референс на метод RequestMapper::toRequestDto

2022-09-21 21:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/unittests/BookingTests.java
> +
Можно бы добавить еще тест на неправильную пагинацию - checkingPageParameters

2022-09-21 21:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/integrationtests/UserTests.java
> +
Есть еще методы удаления

2022-09-22 07:06 UTC, NatalieFilippi commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +
Насколько я поняла, в этом блоке тестируется взаимодействие с базой, сервис и его методы не участвуют в тестировании. Метод checkingPageParameters тестируется в unit тестах

2022-09-22 07:07 UTC, NatalieFilippi commented on src/test/java/ru/practicum/shareit/unittests/ItemRequestTests.java
> +}
Есть такой тест, чуть выше, называется void createFailUser(), 106 строка

2022-09-22 07:11 UTC, NatalieFilippi commented on src/test/java/ru/practicum/shareit/unittests/ItemRequestTests.java
> +}
А, поняла, там другой тест. Добавила.

2022-09-22 07:24 UTC, NatalieFilippi commented on src/test/java/ru/practicum/shareit/integrationtests/UserTests.java
> +
В unit тестах не понимаю, как корректно тестировать удаление, ведь методы ничего не возвращают, а репозиторий подменён моком. Удаление протестировано в слое rest.

2022-09-22 07:29 UTC, alexache commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +
Ошибся классом, куда отписал коммент, да, это хорошо бы в юнит тестах, Не вижу в юнит тесте негативного сценария, где передаются некорректные данные страниц

2022-09-22 07:30 UTC, alexache commented on src/test/java/ru/practicum/shareit/integrationtests/UserTests.java
> +
У мокито есть чудесные методы отслеживания вызовов моков - verify и прочее, можно проверить что при удалении в сервисе вызывается удаление в репозитории.
Тест в рест не проверяет код в сервисе ибо он замокан

2022-09-22 08:54 UTC, NatalieFilippi commented on src/test/java/ru/practicum/shareit/datajpatests/BookingTests.java
> +
Добавила

2022-09-26 10:40 UTC, merged